from controller.CalculadorController import CalculadorController
from controller.MayorMenorController import MayorMenorController
from controller.ComboCascadaController import ComboCascadaController 
from controller.ComboSimpleController import ComboSimpleController

formulario = MayorMenorController()
